### ISSUE TITLE
Environment package versions

### ISSUE THREAD

**Issue by illorens** [pangeo-data/WeatherBench#10]
Hi, sorry to ask for it again but I really think it would be useful to add the package versions to your environment.yml file! Your scripts don't work with tensorflow > 2, and just for general reproducibility it would be nice to know which environment you used. Thank you very much again!

**Comment by raspstephan** [comment]
I added the versions that I used! Thanks for prodding me :) #11

**Comment by illorens** [comment]
Thanks a lot! :)
