### ISSUE TITLE
Package versions not found (using environment.yml)

### ISSUE THREAD

**Issue by ciaron** [pangeo-data/WeatherBench#12]
When I try to create the conda env with `conda env create -f environment.yml` I get the following error:

```Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound: 
  - netcdf4=1.5.2
  - configargparse=0.15.1
  - tensorflow=0.14
```

`conda search` on the default channel and conda-forge show that these version numbers are, in fact, missing. Am I doing something wrong?

**Comment by djgagne** [comment]
That is a really old version of tensorflow (tensorflow is now on 2.1.0), netcdf4 1.5.2 does not appear in the conda-forge archive, and configargparse has newer versions now.

**Comment by ciaron** [comment]
Yep - and these version numbers are in the `environment.yml` commited 12 days ago, hence my confusion.

**Comment by raspstephan** [comment]
Working on it. Should be fixed tomorrow. Sorry about the confusion

**Comment by raspstephan** [comment]
Thanks for pointing out these issues. I have now made some changes (see #13) that should hopefully resolve this. 

About netcdf, I installed it via pip for some reason, which seems to have different version numbers than conda.
