### ISSUE TITLE
PeriodicConv2D and the quickstart notebook

### ISSUE THREAD

**Issue by redouanelg** [pangeo-data/WeatherBench#14]
Hi, thanks for your nice work !

The quickstart notebook seems to use the older version of PeriodicConv2D, the following code raises the error: TypeError: ('Keyword argument not understood:', 'activation')

```python
cnn = keras.models.Sequential([
    PeriodicConv2D(filters=32, kernel_size=5, activation='relu', input_shape=(32, 64, 1,)),
    PeriodicConv2D(filters=1, kernel_size=5)
])
```
Could be because the new PeriodicConv2D inherits from Layer and not Conv2D?

Best.

**Comment by redouanelg** [comment]
I found 

``` python
cnn = keras.models.Sequential([
    PeriodicConv2D(filters=32, kernel_size=5, conv_kwargs={'activation':'relu'}, input_shape=(32, 64, 1,)),
    PeriodicConv2D(filters=1, kernel_size=5)
])
```
to be a working solution.

**Comment by raspstephan** [comment]
Thanks so much for pointing this out! I fixed it!
