### ISSUE TITLE
What is the variable name in the baselines folder?

### ISSUE THREAD

**Issue by EkasitP** [pangeo-data/WeatherBench#16]
Hi.

First of all, thank you for making the WeatherBench. This really helps my research having a benchmark for climate forecasting.

According to the data that you provided in https://dataserv.ub.tum.de/index.php/s/m1524895, I have a question that what is the variable name in the baselines folder. I tried using netCDF4 to read all .nc files, it turns out the parameter name is z (which is the geopotential). I think this geopotential might be 500 hPa geopotential (Z500)? I just want to make sure my understanding.

Best regards,
Ekasit

**Comment by raspstephan** [comment]
Hi, thanks for using the dataset. You can find a list of all the long and short names for the variables in the paper: http://arxiv.org/abs/2002.00469

So z is geopotential. On the download server there is a folder named `geopotential_500` which contains only the Z500 field, and there is a `geopotential` folder which contains all vertical levels. 

Hope this helps.
![image](https://user-images.githubusercontent.com/2786927/82020150-e3376b00-9688-11ea-9723-337bfecbf2ca.png)
