### ISSUE TITLE
Baseline skills data

### ISSUE THREAD

**Issue by illorens** [pangeo-data/WeatherBench#19]
Hello, 
Would you mind including the RMSE, MAE and ACC scores of your baselines (IFS, iterative CNN, persistence and climatologies)? They would be very useful to reproduce the plots without having to download data or train models. 

Thank you very much! :)

**Comment by raspstephan** [comment]
Hi,
check out the rmse.pkl, mae.pkl and acc.pkl files here: https://dataserv.ub.tum.de/index.php/s/m1524895?path=%2Fbaselines

These contain dictionaries of xarray files containing the scores.

Here you can see how they are used: https://github.com/pangeo-data/WeatherBench/blob/master/notebooks/4-evaluation.ipynb

Hope this helps!

**Comment by illorens** [comment]
Thank you!
