### ISSUE TITLE
Reimplementing jweyn's cubesphere unet

### ISSUE THREAD

**Issue by mountain** [pangeo-data/WeatherBench#20]
Hi, buddies, I am not sure my question is proper for this repo, but I can not found any other webpages to ask for.

We are trying to reimplement @jweyn 's cube-sphere unet which is the leading benchmark so far, 
and my question is on the detail commands of tempest-remap tool.

We had read the document and understand the basic workflow, but tempest-remap tool have many options.
So, @jweyn , could you elaborate the detail commands to map the weatherbench data into cube-sphere grids?

Also, we want to verify whether the benchmark was achieved  at 2.8125deg or 1.40625deg dataset.

Thanks.

Mingli

**Comment by jweyn** [comment]
Hi @mountain, thanks for the interest! We are almost done submitting revisions to our paper so I will post the code repository online soon. There is a concrete example usage of the tempest-remap library in there. Stay tuned!

Also, I submitted forecasts at 2º resolution to @raspstephan who then computed the benchmark metrics, so you should ask him what the resolution was (but I guess 2.8).

**Comment by jweyn** [comment]
Apparently it was verified at 5.625 degrees (see [here](https://github.com/pangeo-data/WeatherBench/blob/master/notebooks/Weyn2020-scores.ipynb)).

**Comment by mountain** [comment]
Thanks! We are waiting for your update.

**Comment by jweyn** [comment]
Hi @mountain, just letting you know that we submitted revisions and therefore our code (with examples) is now available [here](https://github.com/jweyn/DLWP-CS). You can find all the commends for tempest-remap in the methods in `DLWP/remap/cubsephere.py`. Feel free to open any issues on my repository if you have questions.

**Comment by mountain** [comment]
Thank you very much!
