### ISSUE TITLE
Understanding changes in data

### ISSUE THREAD

**Issue by devendra-badhe** [pangeo-data/WeatherBench#21]
Hi Team,

I was excitedly working on downloading this data in April 2020. I noticed that since then, there are a few changes:
1. Some files which I had downloaded earlier have grown in size. 
      -eg: potential_vorticity under 1.40625deg

2. Some of the files are missing from there previous locations 
      -eg:relative_humidity under 2.8125deg

3. completely new folder found : CMIP

Can you please clarify the nature of these changes? 
Also, how frequently does the data change?

**Comment by raspstephan** [comment]
Hi, 
sorry, I should have mentioned in the description that the data has been changed. I have now added a Note to the README. There are now more vertical levels, which increases the size of the data. And I've added CMIP data. This is experimental though.

And thanks for noticing the missing data. This is not intended. If you click the ftp link on the data download site, the data is available. I will try to get this sorted out ASAP.

**Comment by raspstephan** [comment]
The data should now be visible on the download server. Thanks again for pointing this out. I will close this issue but let me know if you have any further questions.

**Comment by devendra-badhe** [comment]
Great! Thanks for such a quick response. 

A few follow up questions:
1. Does this change affect the old vertical's data? 
2. In readme, you mentioned that 1 and 10 are added. Do you mean 1 hPa and 10 hPa?
2. Do we have a data dictionary for this data?
