### ISSUE TITLE
"Downloads with FTP" doesn't seem to be working

### ISSUE THREAD

**Issue by rhinoB51** [pangeo-data/WeatherBench#22]
Hi,
I'm looking for FTP config to connect and explore the data available on the site. However, the "downloads with FTP" link seems to be down or moved over to a new URL.
Could you please direct me over to the correct one. Thanks!

ERROR: 
This site can’t be reached
The webpage at ftp://m1524895:m1524895@dataserv.ub.tum.de/ might be temporarily down or it may have moved permanently to a new web address.
ERR_NO_SUPPORTED_PROXIES

Link Text:
Page: https://mediatum.ub.tum.de/1524895
View and download (5.8 TB total, 315 files)
The data server also offers **downloads with FTP**

**Comment by raspstephan** [comment]
Hi,
thanks for your interest in the data. When I click the ftp link from the mediaTUM website, I get forwarded to the correct site which allows me to download the data. For example, this is the link to download all 5.625 degree data: ftp://m1524895:m1524895@dataserv.ub.tum.de/5.625deg/all_5.625deg.zip

Alternatively, you can click the "View and download data" link to download the data. To do so with wget, for example, check the examples in the README page, e.g.: `wget "https://dataserv.ub.tum.de/s/m1524895/download?path=%2F5.625deg&files=all_5.625deg.zip" -O all_5.625deg.zip`

Let me know if this helps.

**Comment by rhinoB51** [comment]
Thanks @raspstephan! I'm trying to download this on a unix server and need to set firewall rule to allow traffic. What's the IP address I can whitelist?

**Comment by raspstephan** [comment]
I just asked, hopefully they will get back to me soon.

**Comment by raspstephan** [comment]
Hi @rhinoB51, is this still an issue? If yes, I would follow up on this again.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @rhinoB51)
