### ISSUE TITLE
Blog post on Weatherbench / weather forecasting with DL

### ISSUE THREAD

**Issue by skeydan** [pangeo-data/WeatherBench#28]
Hi,

just wanted to let you know I've written a post about your dataset / the simple CNN baseline on the RStudio AI blog, for an audience of DL people who are not too familiar with meteorology:

https://blogs.rstudio.com/ai/posts/2020-09-01-weather-prediction/

I'd certainly be happy to (loosely) continue on that topic, but future posts would probably have to feature more complex models trained on (much) more data - which is hard to do without corresponding hardware resources ... However, just in case you ever had an idea for something suitable (if even you're interested in someone writing posts about it, which of course I don't know) do let me know :-)))

**Comment by raspstephan** [comment]
Hi,

this is so cool! First of all, a really well written article with a great introduction to weather forecasting. Then I think it's super cool to have R code for using WeatherBench. 

Yes, I feel the pain of huge data amounts. I really struggled in my latest paper. Maybe you could look at a problem that's easier. For example, predicting the El Nino index works really well even with small data amounts. Look for example at this paper: https://www.nature.com/articles/s41586-019-1559-7

Let me know if you need more ideas.

**Comment by skeydan** [comment]
Hi Stephan,

so happy to hear you like it :-)

That paper looks interesting, and it confirms my impression from your ultra-newest one, that really pre-training / transfer learning matter a lot, probably more than the exact characteristics of the model...?

In fact, I stumbled over another paper that seems very interesting to me, as it combines a topic of high practical relevance for blog readers (insurance companies, etc ...) with theoretical interest (mixes super-resolution, attention mechanisms ...) and ... well ... practical interest (to me ;-)) : high-res rainfall prediction (https://arxiv.org/pdf/2008.09090.pdf)

I haven't checked out their code yet (literally not), but they have a github repo, and that is very important to me, so I have something concrete to start from when starting to port things to R (especially for the data/preprocessing side of things, this is very important, when you're not in expert in the area yourself...)

(((Aside: Your repo is really awesome!)))

Back to the above paper, I fantasize it might be nice to "replicate" on more local (Alpine? ;-))) data, or even try if it transfers to snowfall ... (yeah, that would be the practical interest ;-))
