### ISSUE TITLE
[suggestion] supply zip file in parts

### ISSUE THREAD

**Issue by frankang** [pangeo-data/WeatherBench#29]
The data files with over hundreds of GB (e.g. potential_vorticity_1.40625deg.zip, 420GB) are very hard for rsync/https download (not easy/slow to recover from connection errors). 
Could you provide these data in zip parts file (with each part file smaller than 4GB) to alleviate the download problem? Thanks.

**Comment by raspstephan** [comment]
Yes, I understand it's hard to download one huge file. However, it's not that straightforward for me to upload new data to the server. 

Maybe you could try using the data downloading pipeline directly (https://github.com/pangeo-data/WeatherBench#data-processing). This takes a while but is fail-proof.

**Comment by frankang** [comment]
Thanks for the instructions, well ... may be you can supply zip parts file when adding new data next time...

BTW, could you also share command that generates the `checksums.sha512` file? So we can easily check if any downloaded file corrupts.

**Comment by frankang** [comment]
> Thanks for the instructions, well ... may be you can supply zip parts file when adding new data next time...
> 
> BTW, could you also share command that generates the `checksums.sha512` file? So we can easily check if any downloaded file corrupts.

oops, I just found this `sha512sum --quiet -c checksums.sha512p1` works. And I previously use `awk 'NR%3==1' checksums.sha512 > checksums.sha512p2` to split it into parts to make use of parallelism.

**Comment by raspstephan** [comment]
Great, thanks for figuring this out! And I agree that providing smaller files would be useful. I will keep that in mind and try to change it at some future iteration of the dataset. For now I will close this issue.
