### ISSUE TITLE
toa_incident_solar_radiation_1979_5.625deg.nc is missing the first 7 time points

### ISSUE THREAD

**Issue by shoyer** [pangeo-data/WeatherBench#33]
All the other variables start at `1970-01-01T00:00:00`, but this variable starts at `1970-01-01T07:00:00`. This isn't a big deal, but means makes processing the data a little trickier:
```
In [3]: xarray.open_dataset('/Users/shoyer/Downloads/toa_incident_solar_radiation_1979_5.625deg.nc')
Out[3]:
<xarray.Dataset>
Dimensions:  (lat: 32, lon: 64, time: 8753)
Coordinates:
  * lon      (lon) float64 0.0 5.625 11.25 16.88 ... 337.5 343.1 348.8 354.4
  * lat      (lat) float64 -87.19 -81.56 -75.94 -70.31 ... 75.94 81.56 87.19
  * time     (time) datetime64[ns] 1979-01-01T07:00:00 ... 1979-12-31T23:00:00
Data variables:
    tisr     (time, lat, lon) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2019-12-07 20:42:10 GMT by grib_to_netcdf-2.14.0: /opt/ecmw...
```

I have not checked yet if this is also true in the high-resolution files.

**Comment by shoyer** [comment]
There's the same issue for "tp" (Total precipitation). I'm guessing this may have something to do with the nature of these variables.

**Comment by raspstephan** [comment]
Yes, this is a known issue for ERA, see #6. I handled it by setting `xr.merge(ds, fill_value=0)`. I guess this could be followed by `ds.isel(time=slice(7, None))` to make sure only correct values are in there.

**Comment by shoyer** [comment]
Ah, this sounds vaguely familiar from dealing with ECMWF data years ago. Maybe worth a note in the readme :)

**Comment by ghiggi** [comment]
I also noticed that. Actually all forecast variable of ERA5 start only at 1979-01-01T07:00:00.
Additionally, regarding TOA / tisr data, I noticed that if you monthly/weekly/weeklyhourly standardize pixel-wise the data you have  data points with std anomalies up to 28 deviations ... be careful  ;) 
Best :)

**Comment by shoyer** [comment]
> Additionally, regarding TOA / tisr data, I noticed that if you monthly/weekly/weeklyhourly standardize pixel-wise the data you have data points with std anomalies up to 28 deviations ... be careful ;)

These are bad model outputs? or something else?

I recall that some of these forecast variables are reported as a cumulative "accumulations" from the start of the forecast period (rather than being instantaneous quantities). I wonder if that could be the case here...

**Comment by raspstephan** [comment]
Hmm, I think what might be happening here is that some points of the globe will not get any solar radiation at all during parts of the year. So if you imagine taking a point which only gets sunlight on a the last day of the month, while all other tisr values will be zero, then this one day will have a huge standard deviation. 

This is just a hypothesis though and I did not test it.

**Comment by ghiggi** [comment]
Variations in TOA depends on variation of eccentricity, axial tilt (obliquity), and precession of Earth. 
If interannual variations are really small, you end up with a really small standard deviation which causes the standard anomalies to explode ;)
