### ISSUE TITLE
Doubts reg load parameter in instatiating a DataGenerator 

### ISSUE THREAD

**Issue by aryax265** [pangeo-data/WeatherBench#37]
Should load parameter in instantiating a DataGenerator be set to False when loading huge (say 28 years of data) for training and validation?

**Comment by raspstephan** [comment]
That depends on how much RAM you have. If you set load to False, loading the data directly from disk will take a very long time. So my first suggestion is to try to get access to a big-RAM machine. For my experiments, for example, I had a 700GB RAM machine. I know that this is luxury and probably not practical for everyone. Depending on how many fields you are loading, 100GM should be good. 

If this is still an issue, you can look into [TFRecords](https://www.tensorflow.org/tutorials/load_data/tfrecord). I wrote a TFRecord pipeline in my WeatherBench [branch](https://github.com/raspstephan/WeatherBench), so feel free to explore that. Unfortunately, it is not straight-forward.
