### ISSUE TITLE
Quick question about predictions from test data on any given day

### ISSUE THREAD

**Issue by codenust** [pangeo-data/WeatherBench#40]
Hello,

I have a question about direct predictions using CNN. In the example the test data is used to make predictions for the entire 2017 and 2018. The first test date is 1 January 2017 00UTC,  I wanted to know if I were to see the predictions for any given day in 2017 for example on June 1st 2017 would it be right if I simply plot z or t on June 1st from the given predictions. Does that mean that June 1st prediction would have been conditioned on inputs from the test data on May 31st?

**Comment by raspstephan** [comment]
I think you are correct. For the direct predictions, the date given (e.g. June 1st) is the valid date, so for a 3 day day forecast, the inputs would be May 29.

**Comment by codenust** [comment]
Okay. Thank you!
