### ISSUE TITLE
"tisr" data missing for first 7 hours

### ISSUE THREAD

**Issue by raspstephan** [pangeo-data/WeatherBench#6]
The `toa_incident_solar_radiation` file has the first 7 hours missing. Not sure at this point whether this is a feature of the raw data or whether there is a problem in the data processing. 

Since these are only 7 out of 350,000 samples. I am solving this for now by setting `xr.merge(ds, fill_value=0)` in the data_generator.

**Comment by MargaridaBSC** [comment]
The` total_precipitation` file also has the first 7 hours missing.

**Comment by raspstephan** [comment]
Thanks for pointing this out.

Maybe this is a spin up issue. Hopefully this shouldn't be too much of a problem.

**Comment by MargaridaBSC** [comment]
Hi @raspstephan,
 A colleague from work told me: "the missing first 7 hours is something expected as they come from ERA5 and for accumulated variables (precipitation and radiation in this case),
these are forecast variables and as the "simulation" starts in 1979, the
first data available is at the first timestep of the model". Then this is why the first 7hours are missing
