### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Visgean** [pangeo-data/WeatherBench#7]
Hi, I was trying to go through the quickstart guide and I had a problem downloading this file:

```
!wget "https://dataserv.ub.tum.de/s/m1524895/download?path=%2F5.625deg%2Fgeopotential_500&files=geopotential_500_5.625deg.zip" -O geopotential_500_5.625deg.zip


--2020-03-02 14:59:30--  https://dataserv.ub.tum.de/s/m1524895/download?path=%2F5.625deg%2Fgeopotential_500&files=geopotential_500_5.625deg.zip
Resolving dataserv.ub.tum.de (dataserv.ub.tum.de)... 138.246.224.34, 2001:4ca0:800::8af6:e022
Connecting to dataserv.ub.tum.de (dataserv.ub.tum.de)|138.246.224.34|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-02 14:59:31 ERROR 404: Not Found.
```

**Comment by Zhong0Yuxing** [comment]
I had the same problem. Seems the origin file has expired or been deleted.
![image](https://user-images.githubusercontent.com/45934561/75696677-edcba080-5ce6-11ea-8999-8297f3859643.png)

**Comment by Visgean** [comment]
You can download the full files, including this one from https://mediatum.ub.tum.de/1524895 

look here: 
![image](https://user-images.githubusercontent.com/193832/75707392-b93ff080-5cb6-11ea-84df-546e51cf615d.png)

it was a bit confusing to me so i did not notice at first but this page has all the files...

**Comment by raspstephan** [comment]
Hey, I noticed that the link "View and download" seems to be down. `rsync` doesn't seem to work either...

I will try to fix this ASAP. Thanks so much for letting me know.

**Comment by Visgean** [comment]
have not tried the view and download link, but the ftp worked for me...

**Comment by Zhong0Yuxing** [comment]
Thank you. FTP worked for me too.

**Comment by raspstephan** [comment]
Apparently, there are some issues on the server side, which is why the download link and rsync don't work right now, only ftp. But hopefully this should be resolved very soon.

**Comment by raspstephan** [comment]
Everything should be working again.

**Comment by Visgean** [comment]
thanks!
